---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-deployment-event
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-api-token
          mountPath: /mnt/api-token
          readOnly: true
      volumes:
      - name: my-api-token
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aws-secret-event

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-deployment-email
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"    
  template:
    metadata:
      name: nginx-deployment-email
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-api-token
          mountPath: /mnt/api-token
          readOnly: true
      volumes:
      - name: my-api-token
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aws-secret-email